# h2 db
spring:
  datasource:
    hikari.jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
  jpa:
    hibernate:
      direct: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create
  h2:
    console:
      enabled: true