# profile active
spring:
  profiles:
    active: core

---

# core
spring:
  profiles: core
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql : true
    hibernate:
      direct: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 4000MB
      max-request-size: 4000MB
  config:
    use-legacy-processing: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/kingpiggy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: tmdgns2
