# profile active
spring:
  profiles:
    active: local
    include: core

---

# local profile
spring:
  profiles: local
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 4000MB
      max-request-size: 4000MB
  config:
    use-legacy-processing: true

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

web:
  address: "http://localhost:8080"

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

jwt:
  token:
    secretKey: "1234$%^^890HelloWorld!%$#@!9876543210^_^"
    issuer: "KingPiggy"

mybatis:
  mapper-locations: classpath:mapper/*.xml
