# profile active
spring:
  profiles:
    active: local
    include: core

---

# local profile
spring:
  profiles: local
  servlet:
    multipart:
      max-file-size: 4000MB
      max-request-size: 4000MB
  config:
    use-legacy-processing: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /api

web:
  address: "http://localhost:8080"

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql: trace
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  token:
    secretKey: "1234$%^^890HelloWorld!%$#@!9876543210^_^"
    issuer: "KingPiggy"

mybatis:
  mapper-locations: classpath:mapper/*.xml
